<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
   pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
   <head>
      <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
      <!-- JS Imports Start -->
      <script type="text/javascript"
         src="resources/jslib/jquery-1.11.3.min.js"></script>
      <script type="text/javascript" src="resources/jslib/angular.js"></script>
      <script type="text/javascript" src="resources/jslib/angular.min.js"></script>
      <script type="text/javascript" src="resources/jslib/angular-resource.js"></script>
      <script type="text/javascript"
         src="resources/jslib/angular-resource.min.js"></script>
      <script type="text/javascript"
         src="resources/bootstrap/js/bootstrap.min.js"></script>
      <!-- JS Imports End
         <!-- Style sheet imports start-->
      <link rel="stylesheet" href="resources/bootstrap/css/bootstrap.min.css">
      <link rel="icon" type="image/png" href="images/logo.png">
      <!-- Style sheet imports end -->
      <title>Search Coder</title>
   </head>
   <body>
      <div class="container">
      <h1>Welcome To JDA Full Stack Developer</h1>
      <p>
      	Prerequisite
      	<ul>
      		<li> Java above 1.5</li>
      		<li> Apache Tomcat (apache-tomcat-6.0.43)</li>
      		<li> Apache maven </li>
      	</ul>
      	Steps To run
      	<ul>
      		<li> Clone repo from git using  git clone https://github.com/Step1N/SearchCoder.git or Copy the source code</li>
      		<li> Build mvn clean install -DskipTests=true</li>
      		<li> Create xml in apache (LocalDrive:\apache-tomcat-6.0.43\conf\Catalina\localhost\) as searchCoder.xml</li>
      		<li> Provide path of war generated by build in searchCoder.xml</li>
      		<li> Setup DB with root as user and password and jda as database name</li>
      		<li> Search for http://localhost:8080/searchCoder/ in browser</li>
      	</ul>
      </p>
      <blockquote>
      <p>Following End points </p>
         <ul>
            <li><a style="cursor: pointer;" hrf="#"
               onclick="window.open('http://localhost:8080/searchCoder/jda/coder/list?pageNumber=1&pageSize=10')">
               		http://localhost:8080/searchCoder/jda/coder/list?pageNumber=1&pageSize=10
               </a>
            </li>
            <li><a style="cursor: pointer;" hrf="#"
               onclick="window.open('http://localhost:8080/searchCoder/jda/coder/search?name=title&value=574A - Bear and Elections&pageNumber=1&pageSize=10')">
               http://localhost:8080/searchCoder/jda/coder/search?name=title&value=574A - Bear and Elections&pageNumber=1&pageSize=10</a>
            </li>
            <li><a style="cursor: pointer;" hrf="#"
               onclick="window.open('http://localhost:8080/searchCoder/jda/coder/submissions')">
               http://localhost:8080/searchCoder/jda/coder/submissions</a>
            </li>
         </ul>
      </blockquote>
      <pre>
      		Query Param can pass as per data.
      </pre>
   </body>
</html>

